apiVersion: apps/v1
kind: Deployment
metadata:
  name:  goapp
  namespace: default
  labels:
    app:  goapp
spec:
  selector:
    matchLabels:
      app: goapp
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  goapp
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  goapp
        image:  goapp
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        ports:
        - containerPort:  8080
      restartPolicy: Always