name: CD
on:
  push:
    branches:
      - master
  workflow_dispatch:
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: luisfpo
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build image and push
        uses: docker/build-push-actions@v3
        with:
          repository: luisfpo/lab-argocd
          tags: ${{ github.sha }}, latest