name: CD
on:
  push:
    branches:
      - master
  workflow_dispatch:
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: luisfpo
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build image and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: luisfpo/lab-argocd:${{ github.sha }}, luisfpo/lab-argocd:latest
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v3.6.1

      - name: update k8s
        run: |
          cd k8s
          kustomize edit set image goapp=luisfpo/lab-argocd:${{ github.sha }}
          cat kustomization.yaml

      - name: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "action"
          git commit -am "change image tag"

      - name: push
        uses: ad-m/github-push-action@master