name: CD
on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build image and push
        uses: docker/build-push-actions@v1
        with:
          username: luisfpo
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: luisfpo/lab-argocd
          tags: ${{ github.sha }}, latest